#!/usr/bin/env python

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(60, "alloctest")
def test_alloctest():
    r.run_qemu(shell_script([
        'alloctest'
    ]),timeout=300)
    r.match("^memtest: OK$")

@test(40, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests'
    ]), timeout=300)
    r.match('^ALL TESTS PASSED$')

run_tests()

