#!/usr/bin/env python

import re
from gradelib import *

r = Runner(save("xv6.out"))


@test(40, "buddytests")
def test_buddytests():
    r.run_qemu(shell_script([
        'buddytests' 
    ]))

    # 使用正则匹配确认测试结果
    r.match(r"Allocated memory at 0x[0-9a-f]+") 
    r.match(r"Freed memory at 0x[0-9a-f]+") 
    r.match("^buddytests: OK$")
@test(40, "alloctest")
def test_alloctest():
    r.run_qemu(shell_script([
        'alloctest'
    ]))
    r.match("^memtest: OK$")
@test(20, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests'
    ]), timeout=150)
    r.match('^ALL TESTS PASSED$')



run_tests()

